create table users (
    id bigint generated by default as identity primary key,
    email varchar(255) not null,
    password_hash varchar(255) not null,
    nickname varchar(255) not null,
    profile_image_url varchar(255),
    total_earned_checks integer not null,
    current_checks integer not null,
    level integer not null,
    created_at timestamp(6) not null,
    constraint uk_users_email unique (email)
);

create table avatar_items (
    id bigint generated by default as identity primary key,
    category varchar(255) not null,
    name varchar(255) not null,
    price_checks integer not null,
    rarity varchar(255) not null,
    asset_key varchar(255) not null,
    is_default boolean not null,
    constraint uk_avatar_items_asset_key unique (asset_key)
);

create table studies (
    id bigint generated by default as identity primary key,
    leader_user_id bigint not null,
    type varchar(255) not null,
    title varchar(255) not null,
    description varchar(2000) not null,
    start_time time(6) not null,
    end_time time(6) not null,
    start_date date not null,
    end_date date not null,
    repeat_type varchar(255) not null,
    max_members integer not null,
    location_type varchar(255) not null,
    location_text varchar(255) not null,
    rules_text varchar(1000) not null,
    supplies_text varchar(1000) not null,
    caution_text varchar(1000) not null,
    status varchar(255) not null,
    created_at timestamp(6) not null,
    constraint fk_studies_leader_user
        foreign key (leader_user_id) references users (id)
);

create table avatar_profiles (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    body_asset_key varchar(255) not null,
    pupil_asset_key varchar(255) not null,
    eyebrow_asset_key varchar(255) not null,
    eyelash_asset_key varchar(255) not null,
    mouth_asset_key varchar(255) not null,
    equipped_hair_item_id bigint,
    equipped_top_item_id bigint,
    equipped_bottom_item_id bigint,
    equipped_shoes_item_id bigint,
    equipped_pupil_item_id bigint,
    equipped_eyebrow_item_id bigint,
    equipped_eyelash_item_id bigint,
    equipped_mouth_item_id bigint,
    constraint uk_avatar_profiles_user_id unique (user_id),
    constraint fk_avatar_profiles_user
        foreign key (user_id) references users (id) on delete cascade,
    constraint fk_avatar_profiles_equipped_hair
        foreign key (equipped_hair_item_id) references avatar_items (id),
    constraint fk_avatar_profiles_equipped_top
        foreign key (equipped_top_item_id) references avatar_items (id),
    constraint fk_avatar_profiles_equipped_bottom
        foreign key (equipped_bottom_item_id) references avatar_items (id),
    constraint fk_avatar_profiles_equipped_shoes
        foreign key (equipped_shoes_item_id) references avatar_items (id),
    constraint fk_avatar_profiles_equipped_pupil
        foreign key (equipped_pupil_item_id) references avatar_items (id),
    constraint fk_avatar_profiles_equipped_eyebrow
        foreign key (equipped_eyebrow_item_id) references avatar_items (id),
    constraint fk_avatar_profiles_equipped_eyelash
        foreign key (equipped_eyelash_item_id) references avatar_items (id),
    constraint fk_avatar_profiles_equipped_mouth
        foreign key (equipped_mouth_item_id) references avatar_items (id)
);

create table user_avatar_items (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    avatar_item_id bigint not null,
    purchased_at timestamp(6) not null,
    constraint uk_user_avatar_items_user_item unique (user_id, avatar_item_id),
    constraint fk_user_avatar_items_user
        foreign key (user_id) references users (id) on delete cascade,
    constraint fk_user_avatar_items_avatar_item
        foreign key (avatar_item_id) references avatar_items (id) on delete cascade
);

create table study_days_of_week (
    study_id bigint not null,
    day_of_week varchar(255) not null,
    primary key (study_id, day_of_week),
    constraint fk_study_days_of_week_study
        foreign key (study_id) references studies (id) on delete cascade
);

create table study_tags (
    id bigint generated by default as identity primary key,
    study_id bigint not null,
    name varchar(255) not null,
    constraint uk_study_tags_study_name unique (study_id, name),
    constraint fk_study_tags_study
        foreign key (study_id) references studies (id) on delete cascade
);

create table study_memberships (
    id bigint generated by default as identity primary key,
    study_id bigint not null,
    user_id bigint not null,
    role varchar(255) not null,
    status varchar(255) not null,
    joined_at timestamp(6) not null,
    constraint uk_study_memberships_study_user unique (study_id, user_id),
    constraint fk_study_memberships_study
        foreign key (study_id) references studies (id) on delete cascade,
    constraint fk_study_memberships_user
        foreign key (user_id) references users (id) on delete cascade
);

create table study_sessions (
    id bigint generated by default as identity primary key,
    study_id bigint not null,
    session_no integer not null,
    title varchar(255) not null,
    scheduled_at timestamp(6) not null,
    session_type varchar(255) not null,
    place_text varchar(255),
    notice_text varchar(1000),
    attendance_closed_at timestamp(6),
    constraint uk_study_sessions_study_session_no unique (study_id, session_no),
    constraint fk_study_sessions_study
        foreign key (study_id) references studies (id) on delete cascade
);

create table session_participations (
    id bigint generated by default as identity primary key,
    session_id bigint not null,
    user_id bigint not null,
    planned boolean not null,
    updated_at timestamp(6) not null,
    constraint uk_session_participations_session_user unique (session_id, user_id),
    constraint fk_session_participations_session
        foreign key (session_id) references study_sessions (id) on delete cascade,
    constraint fk_session_participations_user
        foreign key (user_id) references users (id) on delete cascade
);

create table attendances (
    id bigint generated by default as identity primary key,
    session_id bigint not null,
    user_id bigint not null,
    status varchar(255) not null,
    checked_by_user_id bigint not null,
    checked_at timestamp(6) not null,
    constraint uk_attendances_session_user unique (session_id, user_id),
    constraint fk_attendances_session
        foreign key (session_id) references study_sessions (id) on delete cascade,
    constraint fk_attendances_user
        foreign key (user_id) references users (id) on delete cascade,
    constraint fk_attendances_checked_by_user
        foreign key (checked_by_user_id) references users (id)
);

create table check_ledger (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    change_type varchar(255) not null,
    amount integer not null,
    reason varchar(255) not null,
    ref_type varchar(255) not null,
    ref_id bigint,
    created_at timestamp(6) not null,
    constraint fk_check_ledger_user
        foreign key (user_id) references users (id) on delete cascade
);

create table posts (
    id bigint generated by default as identity primary key,
    study_id bigint not null,
    author_user_id bigint not null,
    type varchar(255) not null,
    title varchar(255) not null,
    content varchar(3000) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    constraint fk_posts_study
        foreign key (study_id) references studies (id) on delete cascade,
    constraint fk_posts_author_user
        foreign key (author_user_id) references users (id) on delete cascade
);

create table post_comments (
    id bigint generated by default as identity primary key,
    post_id bigint not null,
    author_user_id bigint not null,
    content varchar(1000) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    constraint fk_post_comments_post
        foreign key (post_id) references posts (id) on delete cascade,
    constraint fk_post_comments_author_user
        foreign key (author_user_id) references users (id) on delete cascade
);

create index idx_avatar_items_category_price_name on avatar_items (category, price_checks, name);
create index idx_user_avatar_items_user_id on user_avatar_items (user_id);
create index idx_studies_status_created_at on studies (status, created_at);
create index idx_studies_leader_user_id on studies (leader_user_id);
create index idx_study_tags_study_id on study_tags (study_id);
create index idx_study_memberships_user_status on study_memberships (user_id, status);
create index idx_study_memberships_study_status on study_memberships (study_id, status);
create index idx_study_sessions_study_scheduled_at on study_sessions (study_id, scheduled_at);
create index idx_session_participations_session_id on session_participations (session_id);
create index idx_attendances_user_id on attendances (user_id);
create index idx_check_ledger_user_created_at on check_ledger (user_id, created_at);
create index idx_check_ledger_ref_lookup on check_ledger (user_id, reason, ref_type, ref_id);
create index idx_posts_study_type_created_at on posts (study_id, type, created_at);
create index idx_posts_study_created_at on posts (study_id, created_at);
create index idx_post_comments_post_created_at on post_comments (post_id, created_at);
