spring:
  application:
    name: gonguham-backend
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    org.hibernate.SQL: debug
